# Nome da API da nossa aplicação
spring.application.name=controle-financeiro-api

# Conexão com o SQLite
spring.datasource.url=jdbc:sqlite:controle_financeiro.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Dialeto do Hibernate (Versão Comunitária para Hibernate 6+)
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# O Flyway criará as tabelas. O Hibernate apenas validará se as classes Java correspondem ao banco
spring.jpa.hibernate.ddl-auto=validate

# Flag DEV_MODE que permite senhas com 1 caractere em desenvolvimento (false = mínimo de 6)
app.security.dev-mode=true

# Chave utilizada para assinar e validar os tokens JWT
app.security.secret=chave